[tool.poetry]
name = "gemini-public-api"
version = "0.10.5"
description = ""
authors = ["Michal Polit <mpolit@protonmail.com>"]
readme = "README.md"
packages = [{include = "gemini_public_api"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"
aiohttp = "^3.8.4"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"
pytest-asyncio = "^0.21.0"
coverage = "^7.2.7"
mock = "^4.0.3"
hypothesis = "^6.54.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
